export const exampleStory = `Lyra stood on the ancient, crumbling bridge, the last sentinel between the village of Whisperwood and the encroaching Shadowblight. The air grew cold with its approach, and the forest, once a vibrant sea of green, now pulsed with a sickly, bruised purple. Her blade, crafted from celestial iron, hummed with a low, resonant energy, a small beacon against the gathering gloom. She was a Guardian, bound by a vow to the land, and the blight was an abomination born of pure malice. A low, guttural shriek echoed from the twisted woods, and from the shifting darkness, the first abominations emerged.

They were creatures of pure shadow, their forms twisted and skeletal, with glowing crimson eyes. Lyra met their charge with a fierce grace. She was not a brute; her strength lay in the elegant dance of her blade and the raw magic woven into her movements. With a flick of her wrist, she sent a wave of shimmering light slicing through the lead monster, its form dissolving into smoke. A second creature lunged, and she parried its shadowy claws with a shower of sparks before driving her blade into its chest. The battle was a flurry of steel and light against the oppressive darkness, each swing a testament to her honed skill.

Just as she thought she had cleared the initial wave, the ground trembled. From the deepest part of the blight, a hulking figure clawed its way out of the earth. It was a greater blight fiend, a towering mass of shifting shadows, its four arms ending in razor-sharp claws. Unlike the lesser fiends, it exuded a tangible dread, a force that threatened to crush her spirit before its claws even made contact. Lyra braced herself, her humming blade flaring brighter. She knew this was a different kind of fight—one that would demand every ounce of her strength and every last reserve of her magical energy.

The fiend roared, a sound that ripped through the air, and charged. Lyra dodged its initial sweep, the ground cracking where its claws struck. She parried a second blow, the clang of celestial iron against dense shadow sending a shockwave that threw her back. Her magic was failing to disperse its form; this creature was too solid. With a desperate gasp, she pulled upon a deeper, more volatile power. Her eyes glowed with a fierce, ethereal light as she channeled a concentrated burst of solar magic. It was a forbidden technique, a power that drained a Guardian's life force, but it was her only chance.

A blinding pillar of light erupted from her blade, striking the fiend square in the chest. The roar of the creature turned to a shriek of agony as the light tore through its form, vaporizing it from the inside out. The Shadowblight receded, and the air grew still. Lyra stood alone, panting, the light from her blade dimming. She had won this battle, but the cost was high. A silver line of energy, a physical mark of the magic she had used, now snaked up her arm and across her face. The blight was gone for now, but she knew this was only the beginning, and that with each fight, she would have less of herself to give.`;
